site_name: WP Editor.md

theme: 
  name: material
  features:
    - tabs
  favicon: img/icon.png
  logo: img/icon.png
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  custom_dir: src
  font: false
  palette:
    primary: "blue grey"
    accent: "blue grey"
  
extra_css: [style/style.css]
repo_url: https://github.com/LuRenJiasWorld/WP-Editor.md
edit_uri: https://github.com/LuRenJiasWorld/WP-Editor.md-Docs
markdown_extensions:
  - meta
  - toc:
      permalink: true
      slugify: !!python/name:myslugify.slugify
  - admonition
  - codehilite

plugins:
  - search:
      lang: "ja"
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/LuRenJiasWorld/WP-Editor.md
  manifest: manifest.webmanifest

copyright: Released via <a href="https://creativecommons.org/licenses/by-nc-sa/4.0" target="_blank">Creative Commons BY-NC-SA License</a> by <a href="https://github.com/LuRenJiasWorld" target="_blank">@LuRenJiasWorld</a>

extra_javascript:
  - assets/javascript/worker.js
  
nav:
  - 主页 | 主頁 | Home: index.md
  - 文档 | 文檔 | Documentation:
    - 欢迎 | 歡迎 | Welcome: documentation/index.md
    - 简体中文: 
      - 简介: documentation/zh-cn/index.md
    - 繁體|正體: 
      - 簡介: documentation/zh-tw/index.md
    - English: 
      - Quick start: documentation/en-us/index.md
  - 参与 | 參與 | Get Involved: 
    - 参与 | 參與 | Get Involved: involve/involve.md
    - 简体中文: 
      - 参与开发: involve/zh-cn/develop.md
      - 撰写文档: involve/zh-cn/documentation.md
      - 金钱捐赠: involve/zh-cn/donation.md
      - 加入社区: involve/zh-cn/forum.md
      - 宣传WP Editor.md: involve/zh-cn/recommend.md
    - 繁體|正體: 
      - 參與開發: involve/zh-tw/develop.md
      - 編寫文檔: involve/zh-tw/documentation.md
      - 金錢捐贈: involve/zh-tw/donation.md
      - 加入社區: involve/zh-tw/forum.md
      - 宣傳WP Editor.md: involve/zh-tw/recommend.md
    - English: 
      - Develop WP Editor.md: involve/en-us/develop.md
      - Write Documentations: involve/en-us/documentation.md
      - Sponsor WP Editor.md: involve/en-us/donation.md
      - Join The Community: involve/en-us/forum.md
      - Recommend WP Editor.md: involve/en-us/recommend.md
